In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df1JN =  pd.DataFrame({ 'Teacher': [9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29],
                       'JnTeacherGrade' : [22, 66, 31, 51, 71, 91, 56, 32, 52, 73, 92]})
df2JN =  pd.DataFrame({'Teacher': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30],
                       'JnTeacherGrade': [98, 93, 44, 77, 69, 56, 31, 53, 78, 93, 56, 77, 33, 56, 27]})

df1SN=  pd.DataFrame({ 'Teacher': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29],
                       'SnTeacherGrade' : [39, 49, 55, 77, 52, 86, 41, 77, 73, 51, 86, 82, 92, 23, 49]})
df2SN =  pd.DataFrame({'Teacher': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
                       'SnTeacherGrade': [93, 44, 78, 97, 87, 89, 39, 43, 88, 78]})

In [ ]:
dfJN= pd.concat([df1JN, df2JN], ignore_index=True)
dfJN

    Teacher  JnTeacherGrade
0         9              22
1        11              66
2        13              31
3        15              51
4        17              71
5        19              91
6        21              56
7        23              32
8        25              52
9        27              73
10       29              92
11        2              98
12        4              93
13        6              44
14        8              77
15       10              69
16       12              56
17       14              31
18       16              53
19       18              78
20       20              93
21       22              56
22       24              77
23       26              33
24       28              56
25       30              27

In [ ]:
dfSN= pd.concat([df1SN, df2SN], ignore_index=True)
dfSN

    Teacher  SnTeacherGrade
0         1              39
1         3              49
2         5              55
3         7              77
4         9              52
5        11              86
6        13              41
7        15              77
8        17              73
9        19              51
10       21              86
11       23              82
12       25              92
13       27              23
14       29              49
15        2              93
16        4              44
17        6              78
18        8              97
19       10              87
20       12              89
21       14              39
22       16              43
23       18              88
24       20              78

In [ ]:
df=dfJN.merge(dfSN,how='inner')
df

    Teacher  JnTeacherGrade  SnTeacherGrade
0         9              22              52
1        11              66              86
2        13              31              41
3        15              51              77
4        17              71              73
5        19              91              51
6        21              56              86
7        23              32              82
8        25              52              92
9        27              73              23
10       29              92              49
11        2              98              93
12        4              93              44
13        6              44              78
14        8              77              97
15       10              69              87
16       12              56              89
17       14              31              39
18       16              53              43
19       18              78              88
20       20              93              78

In [ ]:
df=dfJN.merge(dfSN,how='outer')
df

    Teacher  JnTeacherGrade  SnTeacherGrade
0         1             NaN            39.0
1         2            98.0            93.0
2         3             NaN            49.0
3         4            93.0            44.0
4         5             NaN            55.0
5         6            44.0            78.0
6         7             NaN            77.0
7         8            77.0            97.0
8         9            22.0            52.0
9        10            69.0            87.0
10       11            66.0            86.0
11       12            56.0            89.0
12       13            31.0            41.0
13       14            31.0            39.0
14       15            51.0            77.0
15       16            53.0            43.0
16       17            71.0            73.0
17       18            78.0            88.0
18       19            91.0            51.0
19       20            93.0            78.0
20       21            56.0            86.0
21       22            56.0             NaN
22       23            32.0            82.0
23       24            77.0             NaN
24       25            52.0            92.0
25       26            33.0             NaN
26       27            73.0            23.0
27       28            56.0             NaN
28       29            92.0            49.0
29       30            27.0             NaN

In [ ]:
df=dfJN.merge(dfSN,how='left')
df

    Teacher  JnTeacherGrade  SnTeacherGrade
0         9              22            52.0
1        11              66            86.0
2        13              31            41.0
3        15              51            77.0
4        17              71            73.0
5        19              91            51.0
6        21              56            86.0
7        23              32            82.0
8        25              52            92.0
9        27              73            23.0
10       29              92            49.0
11        2              98            93.0
12        4              93            44.0
13        6              44            78.0
14        8              77            97.0
15       10              69            87.0
16       12              56            89.0
17       14              31            39.0
18       16              53            43.0
19       18              78            88.0
20       20              93            78.0
21       22              56             NaN
22       24              77             NaN
23       26              33             NaN
24       28              56             NaN
25       30              27             NaN

In [ ]:
df=dfJN.merge(dfSN,how='right')
df

    Teacher  JnTeacherGrade  SnTeacherGrade
0         1             NaN              39
1         3             NaN              49
2         5             NaN              55
3         7             NaN              77
4         9            22.0              52
5        11            66.0              86
6        13            31.0              41
7        15            51.0              77
8        17            71.0              73
9        19            91.0              51
10       21            56.0              86
11       23            32.0              82
12       25            52.0              92
13       27            73.0              23
14       29            92.0              49
15        2            98.0              93
16        4            93.0              44
17        6            44.0              78
18        8            77.0              97
19       10            69.0              87
20       12            56.0              89
21       14            31.0              39
22       16            53.0              43
23       18            78.0              88
24       20            93.0              78

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/salemprakash/EDA/main/Data/sales.csv')
df.head(10)

,Account,Company,Order,SKU,Country,Year,Quantity,UnitPrice,transactionComplete
0,123456779,Kulas Inc,99985,s9-supercomputer,Aruba,1981,5148,545,False
1,123456784,GitHub,99986,s4-supercomputer,Brazil,2001,3262,383,False
2,123456782,Kulas Inc,99990,s10-supercomputer,Montserrat,1973,9119,407,True
3,123456783,My SQ Man,99999,s1-supercomputer,El Salvador,2015,3097,615,False
4,123456787,ABC Dogma,99996,s6-supercomputer,Poland,1970,3356,91,True
5,123456778,Super Sexy Dingo,99996,s9-supercomputer,Costa Rica,2004,2474,136,True
6,123456783,ABC Dogma,99981,s11-supercomputer,Spain,2006,4081,195,False
7,123456785,ABC Dogma,99998,s9-supercomputer,Belarus,2015,6576,603,False
8,123456778,Loolo INC,99997,s8-supercomputer,Mauritius,1999,2460,36,False
9,123456775,Kulas Inc,99997,s7-supercomputer,French Guiana,2004,1831,664,True

In [ ]:
df['TotalPrice'] = df['UnitPrice'] * df['Quantity']
df.head(10)

,Account,Company,Order,SKU,Country,Year,Quantity,UnitPrice,transactionComplete,TotalPrice
0,123456779,Kulas Inc,99985,s9-supercomputer,Aruba,1981,5148,545,False,2805660
1,123456784,GitHub,99986,s4-supercomputer,Brazil,2001,3262,383,False,1249346
2,123456782,Kulas Inc,99990,s10-supercomputer,Montserrat,1973,9119,407,True,3711433
3,123456783,My SQ Man,99999,s1-supercomputer,El Salvador,2015,3097,615,False,1904655
4,123456787,ABC Dogma,99996,s6-supercomputer,Poland,1970,3356,91,True,305396
5,123456778,Super Sexy Dingo,99996,s9-supercomputer,Costa Rica,2004,2474,136,True,336464
6,123456783,ABC Dogma,99981,s11-supercomputer,Spain,2006,4081,195,False,795795
7,123456785,ABC Dogma,99998,s9-supercomputer,Belarus,2015,6576,603,False,3965328
8,123456778,Loolo INC,99997,s8-supercomputer,Mauritius,1999,2460,36,False,88560
9,123456775,Kulas Inc,99997,s7-supercomputer,French Guiana,2004,1831,664,True,1215784

In [ ]:
df['Company'].value_counts()

Company
My SQ Man                   869
Kirlosker Service Center    863
Will LLC                    862
ABC Dogma                   848
Kulas Inc                   840
Gen Power                   836
Name IT                     836
Super Sexy Dingo            828
GitHub                      823
Loolo INC                   822
SAS Web Tec                 798
Pryianka Ji                 775
Name: count, dtype: int64

In [ ]:
data = np.arange(15).reshape((3,5))
indexers = ['Rainfall', 'Humidity', 'Wind']
dframe1 = pd.DataFrame(data, index=indexers, columns=['Bergen', 'Oslo', 'Trondheim', 'Stavanger', 'Kristiansand'])
dframe1

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

In [ ]:
stacked = dframe1.stack()
stacked

#stacked.unstack()

Rainfall  Bergen           0
          Oslo             1
          Trondheim        2
          Stavanger        3
          Kristiansand     4
Humidity  Bergen           5
          Oslo             6
          Trondheim        7
          Stavanger        8
          Kristiansand     9
Wind      Bergen          10
          Oslo            11
          Trondheim       12
          Stavanger       13
          Kristiansand    14
dtype: int64

In [ ]:
series1 = pd.Series([000, 111, 222, 333], index=['zeros','ones', 'twos', 'threes'])
series2 = pd.Series([444, 555, 666], index=['fours', 'fives', 'sixs'])

frame2 = pd.concat([series1, series2], keys=['Number1', 'Number2'])
frame2.unstack()

         fives  fours   ones   sixs  threes   twos  zeros
Number1    NaN    NaN  111.0    NaN   333.0  222.0    0.0
Number2  555.0  444.0    NaN  666.0     NaN    NaN    NaN