In [93]:
import pandas as pd
import numpy as np

In [94]:
#Let's assume we have a dataframe as shown
data = np.arange(15, 30).reshape(5, 3)
dfx = pd.DataFrame(data, index=['apple', 'banana', 'kiwi',
'grapes', 'mango'], columns=['store1', 'store2', 'store3'])
dfx

        store1  store2  store3
apple       15      16      17
banana      18      19      20
kiwi        21      22      23
grapes      24      25      26
mango       27      28      29

In [95]:
dfx['store4'] = np.nan
dfx.loc['watermelon'] = np.arange(15, 19)
dfx.loc['oranges'] = np.nan
dfx['store5'] = np.nan
dfx['store4']['apple'] = 20.
dfx

/tmp/ipykernel_1028/3731161268.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfx['store4']['apple'] = 20.

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    20.0     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
watermelon    15.0    16.0    17.0    18.0     NaN
oranges        NaN     NaN     NaN     NaN     NaN

In [96]:
dfx.isnull()

            store1  store2  store3  store4  store5
apple        False   False   False   False    True
banana       False   False   False    True    True
kiwi         False   False   False    True    True
grapes       False   False   False    True    True
mango        False   False   False    True    True
watermelon   False   False   False   False    True
oranges       True    True    True    True    True

In [97]:
dfx.notnull()

            store1  store2  store3  store4  store5
apple         True    True    True    True   False
banana        True    True    True   False   False
kiwi          True    True    True   False   False
grapes        True    True    True   False   False
mango         True    True    True   False   False
watermelon    True    True    True    True   False
oranges      False   False   False   False   False

In [98]:
dfx.isnull().sum()

store1    1
store2    1
store3    1
store4    5
store5    7
dtype: int64

In [99]:
dfx.isnull().sum().sum()

np.int64(15)

In [100]:
dfx.count()

store1    6
store2    6
store3    6
store4    2
store5    0
dtype: int64

In [101]:
dfx.store4[dfx.store4.notnull()]

apple         20.0
watermelon    18.0
Name: store4, dtype: float64

In [102]:
dfx.store4.dropna()

apple         20.0
watermelon    18.0
Name: store4, dtype: float64

In [103]:
dfx.dropna(how='all')

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    20.0     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
watermelon    15.0    16.0    17.0    18.0     NaN

In [104]:
dfx.dropna(how='all', axis=1)

            store1  store2  store3  store4
apple         15.0    16.0    17.0    20.0
banana        18.0    19.0    20.0     NaN
kiwi          21.0    22.0    23.0     NaN
grapes        24.0    25.0    26.0     NaN
mango         27.0    28.0    29.0     NaN
watermelon    15.0    16.0    17.0    18.0
oranges        NaN     NaN     NaN     NaN

In [105]:
dfx.dropna(thresh=5, axis=1)

            store1  store2  store3
apple         15.0    16.0    17.0
banana        18.0    19.0    20.0
kiwi          21.0    22.0    23.0
grapes        24.0    25.0    26.0
mango         27.0    28.0    29.0
watermelon    15.0    16.0    17.0
oranges        NaN     NaN     NaN

In [106]:
ar1 = np.array([100, 200, np.nan, 300])
ser1 = pd.Series(ar1)
ar1.mean(), ser1.mean()

(np.float64(nan), np.float64(200.0))

In [107]:
ser2 = dfx.store4
ser2.sum()

ser2.mean()

np.float64(19.0)

In [108]:
ser2.cumsum()

apple         20.0
banana         NaN
kiwi           NaN
grapes         NaN
mango          NaN
watermelon    38.0
oranges        NaN
Name: store4, dtype: float64

In [109]:
filledDf = dfx.fillna(0)
filledDf

            store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    20.0     0.0
banana        18.0    19.0    20.0     0.0     0.0
kiwi          21.0    22.0    23.0     0.0     0.0
grapes        24.0    25.0    26.0     0.0     0.0
mango         27.0    28.0    29.0     0.0     0.0
watermelon    15.0    16.0    17.0    18.0     0.0
oranges        0.0     0.0     0.0     0.0     0.0

In [110]:
dfx.mean()

store1    20.0
store2    21.0
store3    22.0
store4    19.0
store5     NaN
dtype: float64

In [111]:
filledDf.mean()

store1    17.142857
store2    18.000000
store3    18.857143
store4     5.428571
store5     0.000000
dtype: float64

In [112]:
dfx.store4.fillna(method='ffill')

/tmp/ipykernel_1028/4057730406.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.store4.fillna(method='ffill')

apple         20.0
banana        20.0
kiwi          20.0
grapes        20.0
mango         20.0
watermelon    18.0
oranges       18.0
Name: store4, dtype: float64

In [113]:
dfx.store4.fillna(method='bfill')

/tmp/ipykernel_1028/2174360155.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.store4.fillna(method='bfill')

apple         20.0
banana        18.0
kiwi          18.0
grapes        18.0
mango         18.0
watermelon    18.0
oranges        NaN
Name: store4, dtype: float64

In [114]:
#---- IMPUTATION ----

In [115]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer

In [116]:
df = pd.DataFrame(
 {
 "Age": [25, np.nan, 30, 45, 22],
 "Salary": [50000, 60000, np.nan, 80000, 45000],
 "Category": ["A", "B", "A", np.nan, "B"],
 }
)

In [117]:
mean_imputer = SimpleImputer(strategy="mean")
df["Age_Mean"] = mean_imputer.fit_transform(df[["Age"]])

In [118]:
median_imputer = SimpleImputer(strategy="median")
df["Salary_Median"] = median_imputer.fit_transform(df[["Salary"]])

In [119]:
mode_imputer = SimpleImputer(strategy="most_frequent")
df["Category_Mode"] = mode_imputer.fit_transform(df[["Category"]]).ravel()

In [120]:
# 4. MICE Imputation (Multivariate Imputation by Chained Equations)
# Select numerical columns for MICE
num_cols = ["Age", "Salary"]
mice_imputer = IterativeImputer(max_iter=10, random_state=42)
df_mice = df[num_cols].copy()
df_mice.iloc[:, :] = mice_imputer.fit_transform(df_mice)
df["Age_MICE"] = df_mice["Age"]
df["Salary_MICE"] = df_mice["Salary"]
df

,Age,Salary,Category,Age_Mean,Salary_Median,Category_Mode,Age_MICE,Salary_MICE
0,25.0,50000.0,A,25.0,50000.0,A,25.000000,50000.000000
1,NaN,60000.0,B,30.5,60000.0,B,31.766487,60000.000000
2,30.0,NaN,A,30.0,55000.0,A,30.000000,57324.583367
3,45.0,80000.0,NaN,45.0,80000.0,A,45.000000,80000.000000
4,22.0,45000.0,B,22.0,45000.0,B,22.000000,45000.000000