In [18]:
import pandas as pd

df = pd.read_csv("Suicide data.csv")
df.head()

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27820 entries, 0 to 27819
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   country             27820 non-null  object
 1   year                27820 non-null  int64
 2   sex                 27820 non-null  object
 3   age                 27820 non-null  object
 4   suicides_no         27820 non-null  int64
 5   population          27820 non-null  int64
 6   suicides/100k pop   27820 non-null  float64
 7   country-year        27820 non-null  object
 8   HDI for year        8364 non-null   float64
 9    gdp_for_year ($)   27820 non-null  object
 10  gdp_per_capita ($)  27820 non-null  int64
 11  generation          27820 non-null  object
dtypes: float64(2), int64(4), object(6)
memory usage: 2.5+ MB

In [20]:
df.isnull().sum()

country                   0
year                      0
sex                       0
age                       0
suicides_no               0
population                0
suicides/100k pop         0
country-year              0
HDI for year          19456
 gdp_for_year ($)         0
gdp_per_capita ($)        0
generation                0
dtype: int64

In [21]:
df[df["suicides_no"] > 30]

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
96,Albania,1997,male,25-34 years,36,236000,15.25,Albania1997,NaN,"2,359,903,108",793,Generation X
97,Albania,1997,male,15-24 years,33,244400,13.50,Albania1997,NaN,"2,359,903,108",793,Generation X
110,Albania,1998,female,15-24 years,32,295600,10.83,Albania1998,NaN,"2,707,123,772",899,Generation X
123,Albania,1999,male,35-54 years,31,391100,7.93,Albania1999,NaN,"3,414,760,915",1127,Boomers
145,Albania,2001,male,35-54 years,34,378826,8.98,Albania2001,NaN,"4,060,758,804",1451,Boomers
...,...,...,...,...,...,...,...,...,...,...,...,...
27812,Uzbekistan,2014,male,15-24 years,347,3126905,11.10,Uzbekistan2014,0.675,"63,067,077,179",2309,Millenials
27814,Uzbekistan,2014,female,25-34 years,162,2735238,5.92,Uzbekistan2014,0.675,"63,067,077,179",2309,Millenials
27815,Uzbekistan,2014,female,35-54 years,107,3620833,2.96,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation X
27817,Uzbekistan,2014,male,5-14 years,60,2762158,2.17,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z
27818,Uzbekistan,2014,female,5-14 years,44,2631600,1.67,Uzbekistan2014,0.675,"63,067,077,179",2309,Generation Z

In [22]:
df.sort_values(by="population")

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
14167,Kiribati,2000,male,75+ years,0,278,0.00,Kiribati2000,NaN,"67,254,174",928,G.I. Generation
14059,Kiribati,1991,male,75+ years,0,278,0.00,Kiribati1991,NaN,"47,515,189",768,G.I. Generation
14071,Kiribati,1992,male,75+ years,0,286,0.00,Kiribati1992,NaN,"47,737,955",759,G.I. Generation
14107,Kiribati,1995,male,75+ years,0,287,0.00,Kiribati1995,NaN,"56,338,028",855,G.I. Generation
14083,Kiribati,1993,male,75+ years,0,290,0.00,Kiribati1993,NaN,"46,919,625",735,G.I. Generation
...,...,...,...,...,...,...,...,...,...,...,...,...
27101,United States,2006,male,35-54 years,10641,43139910,24.67,United States2006,NaN,"13,855,888,000,000",49666,Boomers
27081,United States,2004,female,35-54 years,3399,43240905,7.86,United States2004,NaN,"12,274,928,000,000",44867,Boomers
27093,United States,2005,female,35-54 years,3209,43509335,7.38,United States2005,0.897,"13,093,726,000,000",47423,Boomers
27117,United States,2007,female,35-54 years,3525,43607902,8.08,United States2007,NaN,"14,477,635,000,000",51585,Boomers
27105,United States,2006,female,35-54 years,3376,43805214,7.71,United States2006,NaN,"13,855,888,000,000",49666,Boomers

In [23]:
df.shape

(27820, 12)

In [24]:
df.sort_values(by="population",ascending=True)

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
14167,Kiribati,2000,male,75+ years,0,278,0.00,Kiribati2000,NaN,"67,254,174",928,G.I. Generation
14059,Kiribati,1991,male,75+ years,0,278,0.00,Kiribati1991,NaN,"47,515,189",768,G.I. Generation
14071,Kiribati,1992,male,75+ years,0,286,0.00,Kiribati1992,NaN,"47,737,955",759,G.I. Generation
14107,Kiribati,1995,male,75+ years,0,287,0.00,Kiribati1995,NaN,"56,338,028",855,G.I. Generation
14083,Kiribati,1993,male,75+ years,0,290,0.00,Kiribati1993,NaN,"46,919,625",735,G.I. Generation
...,...,...,...,...,...,...,...,...,...,...,...,...
27101,United States,2006,male,35-54 years,10641,43139910,24.67,United States2006,NaN,"13,855,888,000,000",49666,Boomers
27081,United States,2004,female,35-54 years,3399,43240905,7.86,United States2004,NaN,"12,274,928,000,000",44867,Boomers
27093,United States,2005,female,35-54 years,3209,43509335,7.38,United States2005,0.897,"13,093,726,000,000",47423,Boomers
27117,United States,2007,female,35-54 years,3525,43607902,8.08,United States2007,NaN,"14,477,635,000,000",51585,Boomers
27105,United States,2006,female,35-54 years,3376,43805214,7.71,United States2006,NaN,"13,855,888,000,000",49666,Boomers

In [25]:
male = df[df["sex"] == "male"]
female = df[df["sex"] == "female"]

combined = pd.concat([male, female], ignore_index=True)

combined.head()

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($),generation
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent
2,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation
3,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers
4,Albania,1987,male,55-74 years,1,137500,0.73,Albania1987,NaN,"2,156,624,900",796,G.I. Generation

In [26]:
gdp = df[["country", "year", "gdp_per_capita ($)"]].drop_duplicates()

merged = pd.merge(
    df,
    gdp,
    on=["country", "year"],
    how="left"
)

merged.head()

,country,year,sex,age,suicides_no,population,suicides/100k pop,country-year,HDI for year,gdp_for_year ($),gdp_per_capita ($)_x,generation,gdp_per_capita ($)_y
0,Albania,1987,male,15-24 years,21,312900,6.71,Albania1987,NaN,"2,156,624,900",796,Generation X,796
1,Albania,1987,male,35-54 years,16,308000,5.19,Albania1987,NaN,"2,156,624,900",796,Silent,796
2,Albania,1987,female,15-24 years,14,289700,4.83,Albania1987,NaN,"2,156,624,900",796,Generation X,796
3,Albania,1987,male,75+ years,1,21800,4.59,Albania1987,NaN,"2,156,624,900",796,G.I. Generation,796
4,Albania,1987,male,25-34 years,9,274300,3.28,Albania1987,NaN,"2,156,624,900",796,Boomers,796

In [27]:
gdp_df = df[["country", "year", "gdp_per_capita ($)"]].drop_duplicates()

gdp_df.head()

    country  year  gdp_per_capita ($)
0   Albania  1987                 796
12  Albania  1988                 769
24  Albania  1989                 833
36  Albania  1992                 251
48  Albania  1993                 437

In [28]:
continent_df = pd.DataFrame({
    "country": [
        "Albania",
        "Argentina",
        "Australia",
        "Austria",
        "Belgium",
        "Brazil"
    ],
    "continent": [
        "Europe",
        "South America",
        "Oceania",
        "Europe",
        "Europe",
        "South America"
    ],
    "income_level": [
        "Upper Middle",
        "Upper Middle",
        "High",
        "High",
        "High",
        "Upper Middle"
    ]
})

continent_df

     country      continent  income_level
0    Albania         Europe  Upper Middle
1  Argentina  South America  Upper Middle
2  Australia        Oceania          High
3    Austria         Europe          High
4    Belgium         Europe          High
5     Brazil  South America  Upper Middle

In [29]:
joined_df = pd.merge(
    gdp_df,
    continent_df,
    on="country",
    how="inner"
)
joined_df

     country  year  gdp_per_capita ($)      continent  income_level
0    Albania  1987                 796         Europe  Upper Middle
1    Albania  1988                 769         Europe  Upper Middle
2    Albania  1989                 833         Europe  Upper Middle
3    Albania  1992                 251         Europe  Upper Middle
4    Albania  1993                 437         Europe  Upper Middle
..       ...   ...                 ...            ...           ...
172   Brazil  2011               14245  South America  Upper Middle
173   Brazil  2012               13283  South America  Upper Middle
174   Brazil  2013               13191  South America  Upper Middle
175   Brazil  2014               12975  South America  Upper Middle
176   Brazil  2015                9431  South America  Upper Middle

[177 rows x 5 columns]